<script>
  import { onMount } from "svelte";
  import Table from "../components/Table.svelte";
  import Filter from "./../components/Filter.svelte";
  import CovidBasicStats from "./../components/CovidBasicStats.svelte";

  import { getWorldData, getDataForCountries } from "../data/request.js";
  import { filterByName } from "../data/helpers.js";
  import _ from "lodash";
  import { goto } from "@sapper/app";

  const fields = ["Cases", "Deaths", "Recovered", "Active", "Critical"];

  const selectFields = ["Cases", "Deaths", "Recovered", "Active", "Critical"];

  let countries = [];
  let showCountries = [];
  let sortBy = "none";
  let search = "";
  let page = 0;
  let worldStats = { cases: 0, deaths: 0, recovered: 0 };
  $: showCountries = filterByName(countries, search);
  $: if (search.length > 0) {
    page = 0;
  }
  let loading = true;
  onMount(async () => {
    countries = await getDataForCountries();
    worldStats = await getWorldData();
    loading = false;
  });

  async function changeLocation(event) {
    await goto(event.detail);
  }
</script>

<style>
  h1 {
    margin: 20px 0;
  }
  .container {
    margin-bottom: 30px;
  }
</style>

<svelte:head>
  <title>Covid-19 Tracker</title>
</svelte:head>
{#if loading}
  <div class="ui container">
    <h1>Covid-19 Tracker</h1>
    <div class="ui active dimmer">
      <div class="ui text loader">Loading</div>
    </div>
  </div>
{/if}

{#if !loading}
  <div class="ui container">
    <h1>Covid-19 Tracker</h1>
    <CovidBasicStats
      deaths={worldStats.deaths}
      recovered={worldStats.recovered}
      cases={worldStats.cases} />
  </div>
  <div class="ui container">
    <h2>Search By Country</h2>
  </div>
  <Filter {selectFields} bind:sortBy bind:search />
  <Table
    on:location={changeLocation}
    {fields}
    {sortBy}
    bind:page
    canNav="true"
    list={showCountries} />
{/if}

<div style="display: none">
  <!-- This is done so that sapper will export everythign -->
  <a href="China">China</a>
  <a href="China/Hubei">China Hubei</a>
  <a href="China/Guangdong">China Guangdong</a>
  <a href="China/Henan">China Henan</a>
  <a href="China/Zhejiang">China Zhejiang</a>
  <a href="China/Hunan">China Hunan</a>
  <a href="China/Anhui">China Anhui</a>
  <a href="China/Jiangxi">China Jiangxi</a>
  <a href="China/Shandong">China Shandong</a>
  <a href="China/Jiangsu">China Jiangsu</a>
  <a href="China/Chongqing">China Chongqing</a>
  <a href="China/Sichuan">China Sichuan</a>
  <a href="China/Heilongjiang">China Heilongjiang</a>
  <a href="China/Beijing">China Beijing</a>
  <a href="China/Shanghai">China Shanghai</a>
  <a href="China/Hebei">China Hebei</a>
  <a href="China/Fujian">China Fujian</a>
  <a href="China/Guangxi">China Guangxi</a>
  <a href="China/Shaanxi">China Shaanxi</a>
  <a href="China/Yunnan">China Yunnan</a>
  <a href="China/Hainan">China Hainan</a>
  <a href="China/Guizhou">China Guizhou</a>
  <a href="China/Tianjin">China Tianjin</a>
  <a href="China/Shanxi">China Shanxi</a>
  <a href="China/Gansu">China Gansu</a>
  <a href="China/Hong Kong">China Hong Kong</a>
  <a href="China/Liaoning">China Liaoning</a>
  <a href="China/Jilin">China Jilin</a>
  <a href="China/Xinjiang">China Xinjiang</a>
  <a href="China/Inner Mongolia">China Inner Mongolia</a>
  <a href="China/Ningxia">China Ningxia</a>
  <a href="China/Qinghai">China Qinghai</a>
  <a href="China/Macau">China Macau</a>
  <a href="China/Tibet">China Tibet</a>
  <a href="Italy">Italy</a>
  <a href="USA">USA</a>
  <a href="USA/Washington">USA Washington</a>
  <a href="USA/New York">USA New York</a>
  <a href="USA/California">USA California</a>
  <a href="USA/Massachusetts">USA Massachusetts</a>
  <a href="USA/Georgia">USA Georgia</a>
  <a href="USA/Colorado">USA Colorado</a>
  <a href="USA/Florida">USA Florida</a>
  <a href="USA/New Jersey">USA New Jersey</a>
  <a href="USA/Oregon">USA Oregon</a>
  <a href="USA/Texas">USA Texas</a>
  <a href="USA/Illinois">USA Illinois</a>
  <a href="USA/Pennsylvania">USA Pennsylvania</a>
  <a href="USA/Iowa">USA Iowa</a>
  <a href="USA/Maryland">USA Maryland</a>
  <a href="USA/North Carolina">USA North Carolina</a>
  <a href="USA/South Carolina">USA South Carolina</a>
  <a href="USA/Tennessee">USA Tennessee</a>
  <a href="USA/Virginia">USA Virginia</a>
  <a href="USA/Arizona">USA Arizona</a>
  <a href="USA/Indiana">USA Indiana</a>
  <a href="USA/Kentucky">USA Kentucky</a>
  <a href="USA/District Of Columbia">USA District Of Columbia</a>
  <a href="USA/Nevada">USA Nevada</a>
  <a href="USA/New Hampshire">USA New Hampshire</a>
  <a href="USA/Minnesota">USA Minnesota</a>
  <a href="USA/Nebraska">USA Nebraska</a>
  <a href="USA/Ohio">USA Ohio</a>
  <a href="USA/Rhode Island">USA Rhode Island</a>
  <a href="USA/Wisconsin">USA Wisconsin</a>
  <a href="USA/Connecticut">USA Connecticut</a>
  <a href="USA/Hawaii">USA Hawaii</a>
  <a href="USA/Oklahoma">USA Oklahoma</a>
  <a href="USA/Utah">USA Utah</a>
  <a href="USA/Kansas">USA Kansas</a>
  <a href="USA/Louisiana">USA Louisiana</a>
  <a href="USA/Missouri">USA Missouri</a>
  <a href="USA/Vermont">USA Vermont</a>
  <a href="USA/Alaska">USA Alaska</a>
  <a href="USA/Arkansas">USA Arkansas</a>
  <a href="USA/Delaware">USA Delaware</a>
  <a href="USA/Idaho">USA Idaho</a>
  <a href="USA/Maine">USA Maine</a>
  <a href="USA/Michigan">USA Michigan</a>
  <a href="USA/Mississippi">USA Mississippi</a>
  <a href="USA/Montana">USA Montana</a>
  <a href="USA/New Mexico">USA New Mexico</a>
  <a href="USA/North Dakota">USA North Dakota</a>
  <a href="USA/South Dakota">USA South Dakota</a>
  <a href="USA/West Virginia">USA West Virginia</a>
  <a href="USA/Wyoming">USA Wyoming</a>
  <a href="USA/Kitsap Wa">USA Kitsap Wa</a>
  <a href="USA/Solano Ca">USA Solano Ca</a>
  <a href="USA/Santa Cruz Ca">USA Santa Cruz Ca</a>
  <a href="USA/Napa Ca">USA Napa Ca</a>
  <a href="USA/Ventura Ca">USA Ventura Ca</a>
  <a href="USA/Worcester Ma">USA Worcester Ma</a>
  <a href="USA/Gwinnett Ga">USA Gwinnett Ga</a>
  <a href="USA/Dekalb Ga">USA Dekalb Ga</a>
  <a href="USA/Floyd Ga">USA Floyd Ga</a>
  <a href="USA/Fayette Ga">USA Fayette Ga</a>
  <a href="USA/Gregg Tx">USA Gregg Tx</a>
  <a href="USA/Monmouth Nj">USA Monmouth Nj</a>
  <a href="USA/Burlington Nj">USA Burlington Nj</a>
  <a href="USA/Camden Nj">USA Camden Nj</a>
  <a href="USA/Passaic Nj">USA Passaic Nj</a>
  <a href="USA/Union Nj">USA Union Nj</a>
  <a href="USA/Eagle Co">USA Eagle Co</a>
  <a href="USA/Larimer Co">USA Larimer Co</a>
  <a href="USA/Arapahoe Co">USA Arapahoe Co</a>
  <a href="USA/Gunnison Co">USA Gunnison Co</a>
  <a href="USA/Kane Il">USA Kane Il</a>
  <a href="USA/Monroe Pa">USA Monroe Pa</a>
  <a href="USA/Philadelphia Pa">USA Philadelphia Pa</a>
  <a href="USA/Norfolk Va">USA Norfolk Va</a>
  <a href="USA/Arlington Va">USA Arlington Va</a>
  <a href="USA/Spotsylvania Va">USA Spotsylvania Va</a>
  <a href="USA/Loudoun Va">USA Loudoun Va</a>
  <a href="USA/Prince Georges Md">USA Prince Georges Md</a>
  <a href="USA/Pottawattamie Ia">USA Pottawattamie Ia</a>
  <a href="USA/Camden Nc">USA Camden Nc</a>
  <a href="USA/Pima Az">USA Pima Az</a>
  <a href="USA/Noble In">USA Noble In</a>
  <a href="USA/Adams In">USA Adams In</a>
  <a href="USA/Boone In">USA Boone In</a>
  <a href="USA/Dane Wi">USA Dane Wi</a>
  <a href="USA/Pierce Wi">USA Pierce Wi</a>
  <a href="USA/Cuyahoga Oh">USA Cuyahoga Oh</a>
  <a href="USA/Weber Ut">USA Weber Ut</a>
  <a href="USA/Bennington County Vt">USA Bennington County Vt</a>
  <a href="USA/Carver County Mn">USA Carver County Mn</a>
  <a href="USA/Charlotte County Fl">USA Charlotte County Fl</a>
  <a href="USA/Cherokee County Ga">USA Cherokee County Ga</a>
  <a href="USA/Collin County Tx">USA Collin County Tx</a>
  <a href="USA/Jefferson County Ky">USA Jefferson County Ky</a>
  <a href="USA/Jefferson Parish La">USA Jefferson Parish La</a>
  <a href="USA/Shasta County Ca">USA Shasta County Ca</a>
  <a href="USA/Spartanburg County Sc">USA Spartanburg County Sc</a>
  <a href="USA/Harrison County Ky">USA Harrison County Ky</a>
  <a href="USA/Johnson County Ia">USA Johnson County Ia</a>
  <a href="USA/Berkshire County Ma">USA Berkshire County Ma</a>
  <a href="USA/Davidson County Tn">USA Davidson County Tn</a>
  <a href="USA/Douglas County Or">USA Douglas County Or</a>
  <a href="USA/Fresno County Ca">USA Fresno County Ca</a>
  <a href="USA/Harford County Md">USA Harford County Md</a>
  <a href="USA/Hendricks County In">USA Hendricks County In</a>
  <a href="USA/Hudson County Nj">USA Hudson County Nj</a>
  <a href="USA/Johnson County Ks">USA Johnson County Ks</a>
  <a href="USA/Kittitas County Wa">USA Kittitas County Wa</a>
  <a href="USA/Manatee County Fl">USA Manatee County Fl</a>
  <a href="USA/Marion County Or">USA Marion County Or</a>
  <a href="USA/Okaloosa County Fl">USA Okaloosa County Fl</a>
  <a href="USA/Polk County Ga">USA Polk County Ga</a>
  <a href="USA/Riverside County Ca">USA Riverside County Ca</a>
  <a href="USA/Shelby County Tn">USA Shelby County Tn</a>
  <a href="USA/St Louis County Mo">USA St Louis County Mo</a>
  <a href="USA/Suffolk County Ny">USA Suffolk County Ny</a>
  <a href="USA/Ulster County Ny">USA Ulster County Ny</a>
  <a href="USA/Volusia County Fl">USA Volusia County Fl</a>
  <a href="USA/Fairfax County Va">USA Fairfax County Va</a>
  <a href="USA/Rockingham County Nh">USA Rockingham County Nh</a>
  <a href="USA/Washington D C">USA Washington D C</a>
  <a href="USA/Montgomery County Pa">USA Montgomery County Pa</a>
  <a href="USA/Alameda County Ca">USA Alameda County Ca</a>
  <a href="USA/Broward County Fl">USA Broward County Fl</a>
  <a href="USA/Lee County Fl">USA Lee County Fl</a>
  <a href="USA/Pinal County Az">USA Pinal County Az</a>
  <a href="USA/Rockland County Ny">USA Rockland County Ny</a>
  <a href="USA/Saratoga County Ny">USA Saratoga County Ny</a>
  <a href="USA/Charleston County Sc">USA Charleston County Sc</a>
  <a href="USA/Clark County Wa">USA Clark County Wa</a>
  <a href="USA/Cobb County Ga">USA Cobb County Ga</a>
  <a href="USA/Davis County Ut">USA Davis County Ut</a>
  <a href="USA/El Paso County Co">USA El Paso County Co</a>
  <a href="USA/Honolulu County Hi">USA Honolulu County Hi</a>
  <a href="USA/Jackson County Or">USA Jackson County Or</a>
  <a href="USA/Jefferson County Wa">USA Jefferson County Wa</a>
  <a href="USA/Kershaw County Sc">USA Kershaw County Sc</a>
  <a href="USA/Klamath County Or">USA Klamath County Or</a>
  <a href="USA/Madera County Ca">USA Madera County Ca</a>
  <a href="USA/Pierce County Wa">USA Pierce County Wa</a>
  <a href="USA/Tulsa County Ok">USA Tulsa County Ok</a>
  <a href="USA/Douglas County Co">USA Douglas County Co</a>
  <a href="USA/Providence County Ri">USA Providence County Ri</a>
  <a href="USA/Chatham County Nc">USA Chatham County Nc</a>
  <a href="USA/Delaware County Pa">USA Delaware County Pa</a>
  <a href="USA/Douglas County Ne">USA Douglas County Ne</a>
  <a href="USA/Fayette County Ky">USA Fayette County Ky</a>
  <a href="USA/Marion County In">USA Marion County In</a>
  <a href="USA/Middlesex County Ma">USA Middlesex County Ma</a>
  <a href="USA/Nassau County Ny">USA Nassau County Ny</a>
  <a href="USA/Ramsey County Mn">USA Ramsey County Mn</a>
  <a href="USA/Washoe County Nv">USA Washoe County Nv</a>
  <a href="USA/Wayne County Pa">USA Wayne County Pa</a>
  <a href="USA/Yolo County Ca">USA Yolo County Ca</a>
  <a href="USA/Santa Clara County Ca">USA Santa Clara County Ca</a>
  <a href="USA/Clark County Nv">USA Clark County Nv</a>
  <a href="USA/Fort Bend County Tx">USA Fort Bend County Tx</a>
  <a href="USA/Grant County Wa">USA Grant County Wa</a>
  <a href="USA/Santa Rosa County Fl">USA Santa Rosa County Fl</a>
  <a href="USA/Williamson County Tn">USA Williamson County Tn</a>
  <a href="USA/New York County Ny">USA New York County Ny</a>
  <a href="USA/Montgomery County Md">USA Montgomery County Md</a>
  <a href="USA/Suffolk County Ma">USA Suffolk County Ma</a>
  <a href="USA/Denver County Co">USA Denver County Co</a>
  <a href="USA/Summit County Co">USA Summit County Co</a>
  <a href="USA/Bergen County Nj">USA Bergen County Nj</a>
  <a href="USA/Harris County Tx">USA Harris County Tx</a>
  <a href="USA/San Francisco County Ca">USA San Francisco County Ca</a>
  <a href="USA/Contra Costa County Ca">USA Contra Costa County Ca</a>
  <a href="USA/Orange County Ca">USA Orange County Ca</a>
  <a href="USA/Norfolk County Ma">USA Norfolk County Ma</a>
  <a href="USA/Maricopa County Az">USA Maricopa County Az</a>
  <a href="USA/Wake County Nc">USA Wake County Nc</a>
  <a href="USA/Westchester County Ny">USA Westchester County Ny</a>
  <a href="USA/Grafton County Nh">USA Grafton County Nh</a>
  <a href="USA/Hillsborough Fl">USA Hillsborough Fl</a>
  <a href="USA/Placer County Ca">USA Placer County Ca</a>
  <a href="USA/San Mateo Ca">USA San Mateo Ca</a>
  <a href="USA/Sonoma County Ca">USA Sonoma County Ca</a>
  <a href="USA/Umatilla Or">USA Umatilla Or</a>
  <a href="USA/Fulton County Ga">USA Fulton County Ga</a>
  <a href="USA/Washington County Or">USA Washington County Or</a>
  <a href="USA/Snohomish County Wa">USA Snohomish County Wa</a>
  <a href="USA/Humboldt County Ca">USA Humboldt County Ca</a>
  <a href="USA/Sacramento County Ca">USA Sacramento County Ca</a>
  <a href="USA/San Diego County Ca">USA San Diego County Ca</a>
  <a href="USA/San Benito Ca">USA San Benito Ca</a>
  <a href="USA/Los Angeles Ca">USA Los Angeles Ca</a>
  <a href="USA/King County Wa">USA King County Wa</a>
  <a href="USA/Cook County Il">USA Cook County Il</a>
  <a href="USA/Skagit Wa">USA Skagit Wa</a>
  <a href="USA/Thurston Wa">USA Thurston Wa</a>
  <a href="USA/Island Wa">USA Island Wa</a>
  <a href="USA/Whatcom Wa">USA Whatcom Wa</a>
  <a href="USA/Marin Ca">USA Marin Ca</a>
  <a href="USA/Calaveras Ca">USA Calaveras Ca</a>
  <a href="USA/Stanislaus Ca">USA Stanislaus Ca</a>
  <a href="USA/San Joaquin Ca">USA San Joaquin Ca</a>
  <a href="USA/Essex Ma">USA Essex Ma</a>
  <a href="USA/Charlton Ga">USA Charlton Ga</a>
  <a href="USA/Collier Fl">USA Collier Fl</a>
  <a href="USA/Pinellas Fl">USA Pinellas Fl</a>
  <a href="USA/Alachua Fl">USA Alachua Fl</a>
  <a href="USA/Nassau Fl">USA Nassau Fl</a>
  <a href="USA/Pasco Fl">USA Pasco Fl</a>
  <a href="USA/Dallas Tx">USA Dallas Tx</a>
  <a href="USA/Tarrant Tx">USA Tarrant Tx</a>
  <a href="USA/Montgomery Tx">USA Montgomery Tx</a>
  <a href="USA/Middlesex Nj">USA Middlesex Nj</a>
  <a href="USA/Jefferson Co">USA Jefferson Co</a>
  <a href="USA/Multnomah Or">USA Multnomah Or</a>
  <a href="USA/Polk Or">USA Polk Or</a>
  <a href="USA/Deschutes Or">USA Deschutes Or</a>
  <a href="USA/Mchenry Il">USA Mchenry Il</a>
  <a href="USA/Lake Il">USA Lake Il</a>
  <a href="USA/Bucks Pa">USA Bucks Pa</a>
  <a href="USA/Hanover Va">USA Hanover Va</a>
  <a href="USA/Lancaster Sc">USA Lancaster Sc</a>
  <a href="USA/Sullivan Tn">USA Sullivan Tn</a>
  <a href="USA/Johnson In">USA Johnson In</a>
  <a href="USA/Howard In">USA Howard In</a>
  <a href="USA/St Joseph In">USA St Joseph In</a>
  <a href="USA/Knox Ne">USA Knox Ne</a>
  <a href="USA/Stark Oh">USA Stark Oh</a>
  <a href="USA/Anoka Mn">USA Anoka Mn</a>
  <a href="USA/Olmsted Mn">USA Olmsted Mn</a>
  <a href="USA/Summit Ut">USA Summit Ut</a>
  <a href="USA/Fairfield Ct">USA Fairfield Ct</a>
  <a href="USA/Litchfield Ct">USA Litchfield Ct</a>
  <a href="USA/Orleans La">USA Orleans La</a>
  <a href="USA/Pennington Sd">USA Pennington Sd</a>
  <a href="USA/Beadle Sd">USA Beadle Sd</a>
  <a href="USA/Charles Mix Sd">USA Charles Mix Sd</a>
  <a href="USA/Davison Sd">USA Davison Sd</a>
  <a href="USA/Minnehaha Sd">USA Minnehaha Sd</a>
  <a href="USA/Bon Homme Sd">USA Bon Homme Sd</a>
  <a href="USA/Socorro Nm">USA Socorro Nm</a>
  <a href="USA/Bernalillo Nm">USA Bernalillo Nm</a>
  <a href="USA/Oakland Mi">USA Oakland Mi</a>
  <a href="USA/Wayne Mi">USA Wayne Mi</a>
  <a href="USA/New Castle De">USA New Castle De</a>
  <a href="USA/Alabama">USA Alabama</a>
  <a href="USA/Puerto Rico">USA Puerto Rico</a>
  <a href="USA/Guam">USA Guam</a>
  <a href="USA/U S Virgin Islands">USA U S Virgin Islands</a>
  <a href="Spain">Spain</a>
  <a href="Germany">Germany</a>
  <a href="Iran">Iran</a>
  <a href="France">France</a>
  <a href="France/France">France France</a>
  <a href="France/St Martin">France St Martin</a>
  <a href="France/Saint Barthelemy">France Saint Barthelemy</a>
  <a href="France/French Polynesia">France French Polynesia</a>
  <a href="France/French Guiana">France French Guiana</a>
  <a href="France/Mayotte">France Mayotte</a>
  <a href="France/Guadeloupe">France Guadeloupe</a>
  <a href="France/Reunion">France Reunion</a>
  <a href="France/New Caledonia">France New Caledonia</a>
  <a href="korea, south">korea, south</a>
  <a href="Switzerland">Switzerland</a>
  <a href="UK">UK</a>
  <a href="UK/Channel Islands">UK Channel Islands</a>
  <a href="UK/Gibraltar">UK Gibraltar</a>
  <a href="UK/Uk">UK Uk</a>
  <a href="UK/Cayman Islands">UK Cayman Islands</a>
  <a href="UK/Montserrat">UK Montserrat</a>
  <a href="UK/Bermuda">UK Bermuda</a>
  <a href="UK/Isle Of Man">UK Isle Of Man</a>
  <a href="Netherlands">Netherlands</a>
  <a href="Netherlands/Netherlands">Netherlands Netherlands</a>
  <a href="Netherlands/Curacao">Netherlands Curacao</a>
  <a href="Netherlands/Aruba">Netherlands Aruba</a>
  <a href="Netherlands/Sint Maarten">Netherlands Sint Maarten</a>
  <a href="Austria">Austria</a>
  <a href="Belgium">Belgium</a>
  <a href="Norway">Norway</a>
  <a href="Sweden">Sweden</a>
  <a href="Australia">Australia</a>
  <a href="Australia/New South Wales">Australia New South Wales</a>
  <a href="Australia/Victoria">Australia Victoria</a>
  <a href="Australia/Queensland">Australia Queensland</a>
  <a href="Australia/South Australia">Australia South Australia</a>
  <a href="Australia/Western Australia">Australia Western Australia</a>
  <a href="Australia/Tasmania">Australia Tasmania</a>
  <a href="Australia/Northern Territory">Australia Northern Territory</a>
  <a href="Australia/Australian Capital Territory">
    Australia Australian Capital Territory
  </a>
  <a href="Portugal">Portugal</a>
  <a href="Brazil">Brazil</a>
  <a href="Canada">Canada</a>
  <a href="Canada/British Columbia">Canada British Columbia</a>
  <a href="Canada/Ontario">Canada Ontario</a>
  <a href="Canada/Alberta">Canada Alberta</a>
  <a href="Canada/Quebec">Canada Quebec</a>
  <a href="Canada/New Brunswick">Canada New Brunswick</a>
  <a href="Canada/Manitoba">Canada Manitoba</a>
  <a href="Canada/Saskatchewan">Canada Saskatchewan</a>
  <a href="Canada/Newfoundland And Labrador">
    Canada Newfoundland And Labrador
  </a>
  <a href="Canada/Prince Edward Island">Canada Prince Edward Island</a>
  <a href="Canada/Nova Scotia">Canada Nova Scotia</a>
  <a href="Canada/Northwest Territories">Canada Northwest Territories</a>
  <a href="Denmark">Denmark</a>
  <a href="Denmark/Denmark">Denmark Denmark</a>
  <a href="Denmark/Faroe Islands">Denmark Faroe Islands</a>
  <a href="Denmark/Greenland">Denmark Greenland</a>
  <a href="Malaysia">Malaysia</a>
  <a href="Turkey">Turkey</a>
  <a href="Czechia">Czechia</a>
  <a href="Japan">Japan</a>
  <a href="Israel">Israel</a>
  <a href="Ireland">Ireland</a>
  <a href="Luxembourg">Luxembourg</a>
  <a href="Ecuador">Ecuador</a>
  <a href="Pakistan">Pakistan</a>
  <a href="Diamond Princess">Diamond Princess</a>
  <a href="Poland">Poland</a>
  <a href="Chile">Chile</a>
  <a href="Finland">Finland</a>
  <a href="Greece">Greece</a>
  <a href="Thailand">Thailand</a>
  <a href="Iceland">Iceland</a>
  <a href="Indonesia">Indonesia</a>
  <a href="Saudi Arabia">Saudi Arabia</a>
  <a href="Qatar">Qatar</a>
  <a href="Singapore">Singapore</a>
  <a href="Romania">Romania</a>
  <a href="Slovenia">Slovenia</a>
  <a href="India">India</a>
  <a href="Philippines">Philippines</a>
  <a href="Russia">Russia</a>
  <a href="Peru">Peru</a>
  <a href="Bahrain">Bahrain</a>
  <a href="Egypt">Egypt</a>
  <a href="Estonia">Estonia</a>
  <a href="Hong Kong">Hong Kong</a>
  <a href="Panama">Panama</a>
  <a href="South Africa">South Africa</a>
  <a href="Argentina">Argentina</a>
  <a href="Croatia">Croatia</a>
  <a href="Mexico">Mexico</a>
  <a href="Lebanon">Lebanon</a>
  <a href="Iraq">Iraq</a>
  <a href="Colombia">Colombia</a>
  <a href="Serbia">Serbia</a>
  <a href="Dominican Republic">Dominican Republic</a>
  <a href="Algeria">Algeria</a>
  <a href="Armenia">Armenia</a>
  <a href="Kuwait">Kuwait</a>
  <a href="Bulgaria">Bulgaria</a>
  <a href="Slovakia">Slovakia</a>
  <a href="San Marino">San Marino</a>
  <a href="Taiwan">Taiwan</a>
  <a href="Uruguay">Uruguay</a>
  <a href="UAE">UAE</a>
  <a href="Lithuania">Lithuania</a>
  <a href="Latvia">Latvia</a>
  <a href="Costa Rica">Costa Rica</a>
  <a href="Hungary">Hungary</a>
  <a href="Bosnia and Herzegovina">Bosnia and Herzegovina</a>
  <a href="Morocco">Morocco</a>
  <a href="North Macedonia">North Macedonia</a>
  <a href="Faeroe Islands">Faeroe Islands</a>
  <a href="Andorra">Andorra</a>
  <a href="Vietnam">Vietnam</a>
  <a href="Jordan">Jordan</a>
  <a href="New Zealand">New Zealand</a>
  <a href="Cyprus">Cyprus</a>
  <a href="Moldova">Moldova</a>
  <a href="Malta">Malta</a>
  <a href="Albania">Albania</a>
  <a href="Brunei">Brunei</a>
  <a href="Cambodia">Cambodia</a>
  <a href="Sri Lanka">Sri Lanka</a>
  <a href="Belarus">Belarus</a>
  <a href="Burkina Faso">Burkina Faso</a>
  <a href="Tunisia">Tunisia</a>
  <a href="Ukraine">Ukraine</a>
  <a href="Venezuela">Venezuela</a>
  <a href="Senegal">Senegal</a>
  <a href="Azerbaijan">Azerbaijan</a>
  <a href="Réunion">Réunion</a>
  <a href="Kazakhstan">Kazakhstan</a>
  <a href="Palestine">Palestine</a>
  <a href="Guadeloupe">Guadeloupe</a>
  <a href="Oman">Oman</a>
  <a href="Georgia">Georgia</a>
  <a href="Trinidad and Tobago">Trinidad and Tobago</a>
  <a href="Martinique">Martinique</a>
  <a href="Uzbekistan">Uzbekistan</a>
  <a href="Afghanistan">Afghanistan</a>
  <a href="Cameroon">Cameroon</a>
  <a href="Liechtenstein">Liechtenstein</a>
  <a href="Cuba">Cuba</a>
  <a href="Channel Islands">Channel Islands</a>
  <a href="DRC">DRC</a>
  <a href="Nigeria">Nigeria</a>
  <a href="Mauritius">Mauritius</a>
  <a href="Bangladesh">Bangladesh</a>
  <a href="Guam">Guam</a>
  <a href="Honduras">Honduras</a>
  <a href="Bolivia">Bolivia</a>
  <a href="Ghana">Ghana</a>
  <a href="Puerto Rico">Puerto Rico</a>
  <a href="Monaco">Monaco</a>
  <a href="Paraguay">Paraguay</a>
  <a href="Macao">Macao</a>
  <a href="Montenegro">Montenegro</a>
  <a href="Guatemala">Guatemala</a>
  <a href="Guyana">Guyana</a>
  <a href="Jamaica">Jamaica</a>
  <a href="Rwanda">Rwanda</a>
  <a href="French Guiana">French Guiana</a>
  <a href="French Polynesia">French Polynesia</a>
  <a href="Togo">Togo</a>
  <a href="Gibraltar">Gibraltar</a>
  <a href="Kenya">Kenya</a>
  <a href="Barbados">Barbados</a>
  <a href="Ivory Coast">Ivory Coast</a>
  <a href="Kyrgyzstan">Kyrgyzstan</a>
  <a href="Maldives">Maldives</a>
  <a href="Tanzania">Tanzania</a>
  <a href="Ethiopia">Ethiopia</a>
  <a href="Mayotte">Mayotte</a>
  <a href="Mongolia">Mongolia</a>
  <a href="Aruba">Aruba</a>
  <a href="Seychelles">Seychelles</a>
  <a href="Bermuda">Bermuda</a>
  <a href="Equatorial Guinea">Equatorial Guinea</a>
  <a href="U.S. Virgin Islands">U.S. Virgin Islands</a>
  <a href="Gabon">Gabon</a>
  <a href="Isle of Man">Isle of Man</a>
  <a href="Saint Martin">Saint Martin</a>
  <a href="Suriname">Suriname</a>
  <a href="Bahamas">Bahamas</a>
  <a href="Greenland">Greenland</a>
  <a href="New Caledonia">New Caledonia</a>
  <a href="Eswatini">Eswatini</a>
  <a href="Cayman Islands">Cayman Islands</a>
  <a href="Curaçao">Curaçao</a>
  <a href="Cabo Verde">Cabo Verde</a>
  <a href="CAR">CAR</a>
  <a href="Congo">Congo</a>
  <a href="El Salvador">El Salvador</a>
  <a href="Liberia">Liberia</a>
  <a href="Madagascar">Madagascar</a>
  <a href="Namibia">Namibia</a>
  <a href="St. Barth">St. Barth</a>
  <a href="Zambia">Zambia</a>
  <a href="Zimbabwe">Zimbabwe</a>
  <a href="Sudan">Sudan</a>
  <a href="Angola">Angola</a>
  <a href="Benin">Benin</a>
  <a href="Bhutan">Bhutan</a>
  <a href="Fiji">Fiji</a>
  <a href="Guinea">Guinea</a>
  <a href="Haiti">Haiti</a>
  <a href="Mauritania">Mauritania</a>
  <a href="Nicaragua">Nicaragua</a>
  <a href="Niger">Niger</a>
  <a href="Saint Lucia">Saint Lucia</a>
  <a href="Nepal">Nepal</a>
  <a href="Antigua and Barbuda">Antigua and Barbuda</a>
  <a href="Chad">Chad</a>
  <a href="Djibouti">Djibouti</a>
  <a href="Dominica">Dominica</a>
  <a href="Eritrea">Eritrea</a>
  <a href="Gambia">Gambia</a>
  <a href="Grenada">Grenada</a>
  <a href="Vatican City">Vatican City</a>
  <a href="Montserrat">Montserrat</a>
  <a href="Mozambique">Mozambique</a>
  <a href="Papua New Guinea">Papua New Guinea</a>
  <a href="St. Vincent Grenadines">St. Vincent Grenadines</a>
  <a href="Sint Maarten">Sint Maarten</a>
  <a href="Somalia">Somalia</a>
  <a href="Syria">Syria</a>
  <a href="Timor-Leste">Timor-Leste</a>
  <a href="Uganda">Uganda</a>
</div>
